name: Run Tests

on:
  push:
  pull_request:

concurrency:
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
  # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Check code syntax and styling
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            pyver: '3.14'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install dependencies
        run: pip install --group lint

      - name: Verify no code issue
        run: flake8 .

  test:
    name: Test ${{ matrix.os }}-${{ matrix.pyver }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        pyver: ['3.14', '3.13', '3.12', '3.11', '3.10', '3.9']
        arch: [x64]
        include:
          # other OS / Arch
          - os: ubuntu-latest
            pyver: '3.14'
            arch: x64
          - os: macos-latest
            pyver: '3.14'
            arch: arm64

          # SciPy requires manual build to install on x86
          # - os: windows-latest
          #   pyver: '3.14'
          #   arch: x86

          # other Python implementations
          - os: ubuntu-latest
            pyver: '3.14t'
            arch: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pyver }}
          architecture: ${{ matrix.arch }}

      - name: Install package
        run: pip install .

      - name: Run tests
        run: python -m unittest

      - name: Verify that optional dependencies can be installed
        # Gradio does not support free-threaded Python
        # required Gradio version does not support Python 3.9
        if: matrix.pyver != '3.14t' && matrix.pyver != '3.9'
        run: pip install .[gui]

      - name: Verify that dependency groups can be installed
        run: pip install --group dev
